#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
#  TV Calendar — one-time setup for PUBLISH + DAILY AUTO-UPDATE
#
#  Run this ONCE on DS-Home. It:
#    1. Stores your GitHub token (asked once, hidden, kept only on this Mac)
#    2. Publishes today's calendar right now
#    3. Installs a launchd job that rebuilds from Aevum + republishes EVERY DAY
#       at 6:30am — fully automatic, no clicks ever again.
#  After this, you never touch it. The calendar tracks your Aevum data daily.
# ─────────────────────────────────────────────────────────────────────────────
cd "$(dirname "$0")" || exit 1
SELF_DIR="$(pwd)"
RESULT="$SELF_DIR/publish-setup-result.txt"
REMOTE_HOST="github.com/2bkj9stccf-gif/ph-tv-calendar.git"
LABEL="com.media.tvcalendar"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
RUNNER="$SELF_DIR/publish_daily.sh"
LOGDIR="$HOME/Library/Logs/MediaStack"; mkdir -p "$LOGDIR"
PY=""
for p in /opt/homebrew/bin/python3.11 /opt/homebrew/bin/python3 /usr/local/bin/python3 /usr/bin/python3; do
    [ -x "$p" ] && PY="$p" && break
done

echo ""
echo "  ╔════════════════════════════════════════════╗"
echo "  ║   TV Calendar — Publish + Daily Auto-Update  ║"
echo "  ╚════════════════════════════════════════════╝"
echo ""

# ── 1. Token + git remote (ask only if not already set up) ──────────────────
if ! git -C "$SELF_DIR" remote get-url origin >/dev/null 2>&1; then
    [ -d .git ] || { git init -q; git branch -M main; }
    echo "  Paste your GitHub token below (it stays hidden and is saved only on"
    echo "  this Mac), then press Return:"
    printf "  Token: "
    read -rs TOKEN; echo
    if [ -z "$TOKEN" ]; then echo "  No token entered — stopping."; exit 1; fi
    git remote remove origin 2>/dev/null
    git remote add origin "https://${TOKEN}@${REMOTE_HOST}"
    git config user.name  "Aevum TV Calendar"
    git config user.email "tv-calendar@localhost"
    unset TOKEN
fi

# ── everything below is safe to log (no token printed) ──────────────────────
{
echo "Run at: $(date '+%Y-%m-%d %H:%M:%S') on $(hostname)"
echo "Python: $PY"

# ── 2. Write the daily runner (rebuilds from Aevum, commits, pushes) ─────────
cat > "$RUNNER" <<RUNNER_EOF
#!/bin/bash
# Auto-generated by Setup Daily Calendar Publishing.command. Rebuilds the TV
# calendar from the live Aevum database and publishes it to GitHub.
cd "$SELF_DIR" || exit 1
TV_CAL_OUT="$SELF_DIR/calendar.ics" "$PY" generate_tv_calendar.py >> "$LOGDIR/tvcalendar.log" 2>&1 || exit 1
git add calendar.ics
git commit -q -m "Daily TV calendar \$(date +%F)" 2>/dev/null || exit 0
git push -q origin main
RUNNER_EOF
chmod +x "$RUNNER"
echo "✓ Daily runner written: $RUNNER"

# ── 3. Publish today's calendar right now ───────────────────────────────────
echo "Publishing today's calendar…"
if bash "$RUNNER"; then
    echo "✅ Published to GitHub."
else
    echo "⚠ Publish step reported a problem — check the token. (events built:"
    grep -c 'BEGIN:VEVENT' calendar.ics 2>/dev/null
fi

# ── 4. Install the daily launchd job (06:30 every day) ──────────────────────
cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>$LABEL</string>
    <key>ProgramArguments</key>
    <array><string>/bin/bash</string><string>$RUNNER</string></array>
    <key>StartCalendarInterval</key>
    <dict><key>Hour</key><integer>6</integer><key>Minute</key><integer>30</integer></dict>
    <key>StandardOutPath</key><string>$LOGDIR/tvcalendar.log</string>
    <key>StandardErrorPath</key><string>$LOGDIR/tvcalendar.log</string>
</dict>
</plist>
PLIST_EOF
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null
if launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null || launchctl load -w "$PLIST" 2>/dev/null; then
    echo "✅ Daily auto-update installed — rebuilds + republishes every day at 6:30am."
else
    echo "⚠ Could not install the daily job (calendar is still published)."
fi

# ── 5. Verify it's actually live on GitHub Pages ────────────────────────────
echo "Verifying the live calendar (give GitHub a few seconds)…"
sleep 6
LIVE="$(curl -fsSL "https://2bkj9stccf-gif.github.io/ph-tv-calendar/calendar.ics" 2>/dev/null)"
if [ -n "$LIVE" ]; then
    echo "events live on GitHub: $(printf '%s' "$LIVE" | grep -c 'BEGIN:VEVENT')"
    echo "The Bear on GitHub:    $(printf '%s' "$LIVE" | grep -c 'The Bear — S5')"
    echo "SNW on GitHub:         $(printf '%s' "$LIVE" | grep -c 'Strange New Worlds — S4E1')"
else
    echo "(GitHub Pages may take a minute to refresh — the push itself succeeded above.)"
fi
echo ""
echo "Done. Saved to publish-setup-result.txt. Paste this window back to Claude."
} | tee "$RESULT"
